allure.results.directory=test-outputs/allure-results
# Sets the directory for results
allure.link.issue.pattern=https://example.org/issue/{}


# Link screenshots specifically to the test steps
allure.link.mylink.pattern=https://example.org/browse/{}
allure.report.hideEnvironment=true
allure.tests.management.enabled=false